### PR TITLE
Add HTTP to share options

### PR DESCRIPTION
**Pull request by mtotschnig**
Evolved from #967 .

### CODE REVIEW

**Comment by mtotschnig** [comment]
TODO: the result from share via http should include some feedback not only in case of failure, that can be shown in snackbar to user (e.g. File successfully written)

**Comment by arnaldotecadm** [comment]
Hi, I 've tested your changes, including the new ones, although the put request is successfully executed, it does not send the file as expected. I tried a few options in my back end, but it did not work. 
 
The most common error I got was something like "the request was rejected because no multipart boundary was found.
 
the closed thing I've got was trying to receive an Object instead of a File(of multipart or request body), in this case, the API receives an Object, which is unreadable/unparseable)
 
In order to make it work, I've added a few lines(before builder.put), so that my API can correctly receive the file

val multiPart = MultipartBody.Builder()
                    .setType(MultipartBody.FORM)
                    .addFormDataPart("file", resourceName, requestBody)
                    .build()

note that in this case, you don't need to concatenate the file name with the target, since it now makes part of the MultipartBody

And if you do not concatenate the target, we don't need to add a forward slash in the "Share exports and Backups" URL

**Comment by arnaldotecadm** [comment]
For reference, what I have used to came up with this solution was: https://commonsware.com/blog/2020/07/05/multipart-upload-okttp-uri.html

**Comment by mtotschnig** [comment]
If I am not mistaken, multipart is not applicable for a PUT request, but is meant to be used with POST. You probably have to tweak your implementation so that it reads the content directly from the request body of the request.

**Comment by arnaldotecadm** [comment]
oh nice tip!

Using HttpServletRequest directly it worked. Although I am not used to receiving HttpServletRequest directly, that's why it was not working.

Anyways, it works and I believe you are good to go: it worked in all scenarios needed (Exports and backups)

nb: Would it be useful to mention on your website how to integrate the API? I mean, the method signature to make the integration possible or even a sample in github?

**Comment by mtotschnig** [comment]
I have created this FAQ entry: https://github.com/mtotschnig/MyExpenses/wiki/FAQ:-Data#what-are-the-different-share-options , and will link to it from the help menu entry in the app.

**Pull request merged**
