### PR TITLE
Improved dialogs

### LINKED ISSUE #237: Improve usability of text input dialog
This dialog is used for example for entering category labels. It has no confirmation button, because it closes upon enter or the "Done" button on the virtual keyboard. Users sometimes get confused by this lack of visible action indicator.

### LINKED ISSUE #319: Reenable custom colors
Currently only a couple of colors can be selected for accounts. Implement chooser for custom colors.

### PR DESCRIPTION
**Pull request by eltos**
- Custom account color picker fixes #319
- Improved text input dialog fixes #237
- Show template edit activity after creation

Old:
old
New:
new

### CODE REVIEW

**Comment by mtotschnig** [comment]
Many thanks for the interesting contribution, and sorry for the late reaction. Main concern at the moment. I am not (yet) inclined to abandon Gingerbread. Your library seems to require API 11. How difficult would it be to provide a graceful fallback on pre 11?

**Comment by eltos** [comment]
Not that difficult - in fact, there is already an API 9 version (see [build.gradle](https://github.com/mtotschnig/MyExpenses/pull/382/files#diff-a9bd7d378bcb2ac73bc75b208a891cc3)).

**Comment by mtotschnig** [comment]
I finally found time for testing it. Thanks again. Unfortunately on Gingerbread, the colour dialog does not work. It crashes with
`
java.lang.NoSuchMethodError: android.widget.AbsListView.setAdapter
                                           at eltos.simpledialogfragment.list.CustomListDialog.onCreateContentView(CustomListDialog.java:339)
                                           at eltos.simpledialogfragment.CustomViewDialog.onCreateDialog(CustomViewDialog.java:188)
                                           at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:312)
                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                           at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                           at android.os.Handler.handleCallback(Handler.java:587)
                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                           at android.os.Looper.loop(Looper.java:130)
                                           at android.app.ActivityThread.main(ActivityThread.java:3683)
                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                           at java.lang.reflect.Method.invoke(Method.java:507)
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
                                           at dalvik.system.NativeStart.main(Native Method)
`

**Comment by eltos** [comment]
That's weird, as `setAdapter` was added in API 1.
I think the accepted Answer (here)[https://stackoverflow.com/questions/7306430/how-to-solve-java-lang-nosuchmethoderror-android-widget-abslistview-isitemcheck] might be helpfull.
I'll try weather an explicit cast to `ListView` does the trick.

**Comment by mtotschnig** [comment]
I have been working on a fix. Will publish a pull request to your library in a minute.

**Comment by mtotschnig** [comment]
One more question with respect to the minSdk9 branch of SimpleDialogFragments library. Do you plan to maintain it actively or will it become a dead end without bug fixes applied to it? Why not integrate it into the master branch with gracefully falling back from api11 to legacy behaviour?

**Comment by eltos** [comment]
This works for me now, can you verify that?

**Comment by mtotschnig** [comment]
Yes it works. Would you accept a pull request for targeting the master branch of your library that makes it work on Gingerbread?

**Comment by eltos** [comment]
I would like to keep api9 support seperated
This allows me to easily add new features and merge them into the minSdk9 branche with propper testing. Also not all functions are backwards portable and I don't want to give the impression that my library is fully compatible by generally lowering the min api to 9.

**Comment by mtotschnig** [comment]
As a developer needing API 9 support at the moment, I am not convinced by this argument. Both testing and documentation of what works on API 9 need to be done independent of if this support happens on main line or a side branch. Moving it to a side branch just indicates that it is considered secondary, and is not guaranteed to happen. Of course I respect and understand that it is not a priority for you. I will probably use my own fork based on your master branch (https://github.com/mtotschnig/SimpleDialogFragments) for MyExpenses. In any case, thanks a lot for your contribution!

**Pull request merged**
