### PR TITLE
New ColorSource TYPE_WITH_SIGN. (Credit/Debit/Transfer)

### PR DESCRIPTION
**Pull request by piriurna**
New ColorSource with Credit/Debit/Transfer categorization for styling. 

This fix is just meant to style the transactions by SIGN but still keeping the transfer and neutral styling for better readability.

There is an open issue about this, relates to https://github.com/mtotschnig/MyExpenses/issues/1423

### CODE REVIEW

**Comment by mtotschnig** [comment]
This does not yet work as is. After checking out your branch, and selecting the new third option, app crashes with:

    java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
    at androidx.preference.ListPreferenceDialogFragmentCompat.onDialogClosed(ListPreferenceDialogFragmentCompat.java:107)
    at androidx.preference.PreferenceDialogFragmentCompat.onDismiss(PreferenceDialogFragmentCompat.java:293)
    at androidx.fragment.app.DialogFragment$3.onDismiss(DialogFragment.java:378)
    at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1470)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

You need to add the new option to string-array pref_transaction_amount_color_source_values in file arrays.xml

**Comment by piriurna** [comment]
Done, I had some problems building the project before, but now i managed to test it and check everything is 100%

Screenshot_20240223_190947

**Comment by mtotschnig** [comment]
@piriurna Many thanks for your contribution. If you are interested, I have done some minor refactoring: 12896258a620306e34144a015ec55c3422119122

**Comment by piriurna** [comment]
That is a much cleaner solution!
Thank you very much for your time and consideration

**Comment by mtotschnig** [comment]
@piriurna FYI: I acknowledge your contribution here: https://mastodon.social/@myexpenses/112019869521610262

**Pull request merged**
