### PR TITLE
New and modified functionality of MyExpenses (transactions, accounts, currencies, statistics, sms parsing, nearby banks etc)

### PR DESCRIPTION
**Pull request by emusatova**
# Greetings

Hello, MyExpenses community!

I represent a team of MSIT-SE students from Innopolis University (Innopolis, Russian Federation).
Our Master's program includes a course named 'Methods: Deciding what to Design'. 

In this course we have a team project. The main idea of the project is to learn how to work with product requirements.
At the beginning of the project we got several tasks:

1. Find an open-source Android project.
2. Find potential customer for this project.
3. Define with customer features to be added, modified and removed from the project.
4. Implement these features.
5. Present our results to the customer and the application community.

All members of our team like the idea of financial management. And we thought that our experience could be useful for you.
And, as you can see, we chose MyExpenses application. 

We have almost completed the work on this project, and want to demonstrate you our results.
It would be great, if you will provide us some feadback about changes that we made. 
Or, maybe, you will find something interesting or useful, and include these features in the future versions of MyExpenses.

# MyExpenses CHANGELOG

## New features

1. Welcome slides with short description about main application features.
2. Currencies screen with a current exchange rate.
3. SMS-parsing for a quickly tracking from the debit/credit cards.
4. Find banks near your and show its' working state. 
5. Notifications not to forget to track expenses.

## Modifications
1. Main application screen
	1.1. Simplify design of transaction list.
	1.2. Redesign of Accounts sidebar.
	1.3. Updates in Application menu.
2. Statistics page
	2.1. Redesign (layout, styles, charts settings).
	2.2. Ability to switch between accounts on statistics page.
3. Interaction with categories
	3.1. Lock ability not to select category of transaction.
	3.2. Restructure categories (change type and remove dublicates).

## Removed features
1. Export/import to QIF format. 
QIF format is used by Microsoft Money. But this service/application is not supported now.
2. Print.
As practice shows, this feature is not used by mobile application users. It is more relevant for the desktop users.
3. Tell a friend.
This function is not often used. The most popular case is recommendations and high rating in Google Play.

### CODE REVIEW

**Comment by lauco74** [comment]
Remove qif format is not a good idea, grisbi and gnucash use it. There is not only Microsoft Money and Windows in the world ! I'm a ubuntu user and use currently grisbi (which exist under MS) with the qif import.

**Comment by mtotschnig** [comment]
Many thanks for this contribution. Sounds impressive! Please give me some time to evaluate.

**Comment by keunes** [comment]
> Find banks near your and show its' working state.

Please also the introduction of this feature. I try to avoid Google as much as possible, and this is an (IMHO) unnecessary addition to the app. There are standalone apps that do the locating of banks perfectly fine, and who do not force me to use proprietary platforms/map data.
If introduced, please use osm maps instead.

**Comment by jimfoo88** [comment]
No, why did you all remove the qif export feature? I need to use it for import into Quicken at desktop. 
I think you all should add more charts, like bar chart to view how much of a budget is remaining for one category. Or a line chart to see your cash flow over a period of time.

**Comment by DSIW** [comment]
Cool ideas! I think it would be better if the different features are in smaller separate pull requests for easier integration. Otherwise it isn't really possible to integrate some changes.

- Intro is great!
- Finding nearby banks isn't required for financial management. Google Maps / OSM are great for this.
- I like the simplified design of transaction list and accounting list. It has more whitespace and is clearer.

**Comment by amkcpu** [comment]
Is there any consideration to add some of the features implemented here?

For my part, I think the intro screens look great, and I like to simpler look of the main view and the side pane, as well as the statistics view.
Also, the currency section (or more generally, an integration of updated currency exchange rates), would be great! And an optional notification to log one's booking would be nice too.

As some of the people before me, I would also not recommend to implement the "find banks" and "SMS tracking" features.

**Comment by mtotschnig** [comment]
@amkcpu As others have mentioned, it is not feasible to deal with a merge request that contains that many changes at once. But a couple of the features are on our roadmap:
- #546 
- #458 
- #388

**Pull request closed without merging**
