### PR TITLE
fix: add transfer category to csv import transfers

### PR DESCRIPTION
**Pull request by creatvty**
I have been trying to get the Transfers working in CSV Import. It was not working 100% because the Transfer Category was not actually assigned as described in https://github.com/mtotschnig/MyExpenses/issues/1487#issuecomment-2275288228

Here I'm trying to add the category to the transfer cases.

### CODE REVIEW

**Comment by creatvty** [comment]
@mtotschnig could you take a look at this?

**Comment by mtotschnig** [comment]
@creatvty thanks for the reminder. I am sorry, it was not on my radar. Am looking into it now.

**Comment by mtotschnig** [comment]
@creatvty Did you actually compile this?

**Comment by creatvty** [comment]
> @creatvty Did you actually compile this?

@mtotschnig I did not. It was more of a proposal. I just poked around a little and tried to debug

**Pull request closed without merging**
